favorite_1:
  name: Favorite 1
  description: Move the blind to the Favorite 1 preset position.
  target:
    entity:
      integration: neosmartblinds_ha
      domain: cover
  icon: "mdi:numeric-1-circle"

favorite_2:
  name: Favorite 2
  description: Move the blind to the Favorite 2 preset position.
  target:
    entity:
      integration: neosmartblinds_ha
      domain: cover
  icon: "mdi:numeric-2-circle"